### ISSUE TITLE
Title Case with Accent

### ISSUE THREAD

**Issue by periscuelo** [leocaseiro/jQuery-Plugin-stringToSlug#13] opened 2016-02-02 14:34 UTC
First I would like to thank everyone for the great script that made. Congratulations and thank you! I believe I have found a bug in the system. If you test this link http://leocaseiro.github.io/jQuery-Plugin-stringToSlug/#js-options-options
a word with accent on the first letter where the Title Case is true he puts the second letter capitalized. For example Ánhanguera change to ANhanguera. Or ánhanguera change to aNhanguera.
Would not it be a bug?
Grateful once again for your attention.

**Comment by leocaseiro** [comment] 2016-02-03 00:01
Hi @periscuelo, thank you for your issue.

The example you mentioned is defined to be used with Arabic language: ```lang: 'ar'``` only.

I'm not sure what language is the word: "Ánhanguera", but I'm sure if you define the correct language(perhaps Portuguese: 'pt'), you'll be fine to slug your string. I've set English for most of my examples, would you like to try in any other field and see how it goes?

PS: The language option uses the [SpeakingURL](http://pid.github.io/speakingurl/) library. The sets are:
```
'ar' // Arabic
'az' // Azerbaijani*
'cs' // Czech
'de' // German
'dv' // Divehi
'en' // English
'es' // Spanish
'fr' // French
'gr' // Greek*
'hu' // Hungarian
'it' // Italian
'lt' // Lithuanian*
'lv' // Latvian
'my' // Burmese
'mk' // Macedonian*
'nl' // Dutch
'pl' // Polish
'pt' // Portuguese
'ro' // Romanian
'ru' // Russian
'sk' // Slovak
'sr' // Serbian*
'tr' // Turkish
'uk' // Ukranian
'vn' // Vietnamese

default: 'en' // ISO 639-1 Codes
```


Hope this answer your question.

**Comment by leocaseiro** [comment] 2016-02-03 00:09
@periscuelo I've just noticed that actually, SpeakingURL has a bug on Portuguese while using titleCase.

I'm going to open an issue to be fixed and I'll get back to you as soon as I see a fix.

**Comment by leocaseiro** [comment] 2016-02-03 00:21
Here is a Plnkr: http://plnkr.co/edit/gTNCaNOACfm1brSletc3?p=preview

**Comment by periscuelo** [comment] 2016-02-03 00:33
@leocaseiro Thanks for the quick response and attention. I'm waiting anxiously. Thanks again.

**Comment by leocaseiro** [comment] 2016-02-03 00:36
The issue is on https://github.com/pid/speakingurl/issues/72

**Comment by pid** [comment] 2016-02-03 21:22
fixed in v9.0.0

**Comment by leocaseiro** [comment] 2016-02-03 22:48
That was quickly, many many thanks.

**Closed by leocaseiro** 2016-02-03 22:48 UTC
Labels: bug, SpeakingURL

**Comment by periscuelo** [comment] 2016-02-10 11:43
Thank you very much for the quickly solution.

**Comment by leocaseiro** [comment] 2016-02-11 00:59
updated on 3cfddc0a0c0f35
